---
include:
  - board: xiao_ble
    shield: corne_central_dongle
  - board: nice_nano
    shield: corne_central_dongle
  - board: nice_nano
    shield: corne_central_left
  - board: nice_nano
    shield: corne_peripheral_left
  - board: nice_nano
    shield: corne_peripheral_right
  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset
